[alias]
run-watch = "watch -c -x check -x run"

[target.'cfg(all(windows, target_env = "msvc"))']
# rustflags = ["-C", "target-feature=+crt-static"]
# # rustflags = ["-C", "link-arg=/MANIFESTUAC:level='requireAdministrator' uiAccess='false'"]
# rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=/MANIFESTUAC:level='requireAdministrator' uiAccess='false'"]
